### ISSUE TITLE
Error signing up to Datacamp

### ISSUE THREAD

**Issue by Douwe31** [janboone/applied-economics#12]
Dear Jan Boone, 

Yesterday I tried to enter the group 'Applied Economic Analysis 2018' on Datacamp by accepting the sent email invitation. However once I sign in I receive an error message saying that I need to contact the admin of the group. How can this be resolved? 

Kind regards, 
Douwe de Wit 
(E: d.t.dewit@tilburguniversity.edu)

**Comment by janboone** [comment]
You are in the group with your @live.nl email address.
