### ISSUE TITLE
Different Introduction courses on Datacamp

### ISSUE THREAD

**Issue by albertgoderie** [janboone/applied-economics#15]
Dear mr Boone,

I want to start the Python Datacamp courses. However, for the introduction course the link on your github pages brings me to this course: https://www.datacamp.com/courses/intro-to-python-for-data-science while the link from your invitation on canvas of yesterday brings me to this course: https://www.datacamp.com/courses/introduction-to-data-science-in-python. Both courses are introduction courses for Python, but they differ in content. 

Which one is the best one to start with?

Kind regards,

Albert

**Comment by janboone** [comment]
Thanks for pointing this out! The course that I meant is: https://www.datacamp.com/courses/intro-to-python-for-data-science

(although there is no problem if you do the other one)
