### ISSUE TITLE
Missed deadline Datacamp

### ISSUE THREAD

**Issue by U1273225** [janboone/applied-economics#16]
Dear professor Boone,

I was not aware that the deadline of the introduction course in Datacamp expired a few days ago, as this was not mentioned in the general schedule on github. Is it a problem if I finish this part now, after the deadline has expired?

Sincerely,

Lars Spaander

**Comment by janboone** [comment]
Actually, it is mentioned on the website: https://janboone.github.io/applied-economics/index.html#org6f6d2ca

Try to stick to the coming deadlines!

Jan.
