### ISSUE TITLE
Question: Final assigment as an starting point of the MSc Thesis?

### ISSUE THREAD

**Issue by jsameijeiras** [janboone/applied-economics#18]
I know that is not the main idea of the final assignment for this course and that in fact we would have applied economics 2 to do that. However, I believe it could be useful for some of us to start preparing as soon as possible for our master thesis and I wonder if you believe this makes sense.

If that is the case could we arrange some office hours with you to see the idea in detail?

**Comment by janboone** [comment]
Thanks for your message. Indeed, making the final assignment a starting point for your thesis is a very good idea. 

This is relevant for all students. Is it ok if we first discuss this in class in October?

**Comment by jsameijeiras** [comment]
Perfect. We can discuss that in October I was asking now because some people are looking for groups already but if we use it as a starting point for the thesis it makes sense to do it alone.
