### ISSUE TITLE
Doing both Python and Canon

### ISSUE THREAD

**Issue by DionnevandenAker** [janboone/applied-economics#19]
Hi!

I'd love to do both the Python and the Canon track. However, which grade will count as my final grade for this course? Would that simply be the highest grade out of both tracks or something else?

Kind regards,
Dionne van den Aker

**Comment by janboone** [comment]
Hi Dionne,

Great that you would like to do both! Indeed, the highest grade will count as the grade for the course.

Regards,

Jan.
