### ISSUE TITLE
Anaconda instal error

### ISSUE THREAD

**Issue by MurielVerbeek** [janboone/applied-economics#2]
Hello,
During the installment of Anaconda it failed to create Anaconda menus. I was able to finish the installation. Is it problematic that I don't have the menus? 
I searched online for quite a while and tried some things but was not able to resolve the error. The error message was 'unicodeencodeerror 'ascii' codec can't encode character u'\xeb' in position 13: ordinal not in range(128)'. At first, I thought it was because my computer username is Muriël since the ë is xeb in Unicode but after trying to install again after changing my username into Muriel, I got the same error. Thanks in advance for the help.

**Comment by janboone** [comment]
Indeed, it is likely that the username is a problem (perhaps there is still a directory name "Muriël" somewhere in the path.

Here is a suggestion to install python 3.0:

https://github.com/jupyter/notebook/issues/646

Could you try this? If there are compatibility issues, I will help you around them during the course.

**Comment by MurielVerbeek** [comment]
Thanks for the quick reply. I also got a reply from the support of Anaconda and I added the menus via the command prompt!

**Comment by janboone** [comment]
well done!

**Comment by janboone** [comment]
can you comment here and copy/paste the reply from anaconda; then others know what to do as well.

Thanks!

**Comment by MurielVerbeek** [comment]
Of course. The solution is specific for Windows 10. The reply was:
"There is an issue with special unicode characters in the username in regards to Windows and Python 2. If you have changed your username to not include the character you can try to reinstall and then run these commands from the Windows Command Prompt, you will probably see the same error upon reinstall.

   conda update menuinst
   conda install -f console_shortcut ipython ipython-notebook ipython-qtconsole anaconda-navigator spyder
This should hopefully create the menu items. If not a general solution is to install Anaconda3 which uses Python 3.5. Python 3 has better handling of unicode and usually does not get this error. With Anaconda3 installed you can still create an environment with Python 2.7 and use it as well. command line – http://conda.pydata.org/docs/using/envs.html, Navigator – https://docs.continuum.io/anaconda/navigator-tutorial."
