### ISSUE TITLE
question empirical research

### ISSUE THREAD

**Issue by florisvanlaarhoven** [janboone/applied-economics#33]
**Question** Plot GPD per head in 1990 against GDP per head in 2017. What do you conclude about the development in inequality in these 27 years?

For the question above, I used the following code:

def y(x):
    y=x
    return y
rangex = np.arange(0,130000,100)

plt.plot(df_merged.GDP_per_head_2017,df_merged.GDP_per_head_1990, 'o')
plt.plot(rangex, [y(x) for x in rangex], '-')
plt.xlabel('GDP per head in 2017')
plt.ylabel('GDP per head in 1990')
plt.show()

I defined the function in order to plot a 45 degree line (x=y) so that I can see whether countries' GDP per head fell or rose. Hence, dots to the right of the 45 degree line saw an increase in GDP per head. However what can we tell about inequality among those countries?

**Comment by janboone** [comment]
Indeed, this was our idea.

Some small things: the 45 degree line can also be plotted as:

``` python
plt.plot([0,130000],[0,130000])
```
which is simpler (but your code is fine too).

We wanted you to make the comparison vis-a-vis the 45 degree line. If all points would be on the 45 degree line, inequality would have been the same in the two years. When high income countries deviate (in the way you describe) more from the 45 degree line than low income countries, inequality has increased.
