### ISSUE TITLE
Can't do the Model questions

### ISSUE THREAD

**Issue by florisvanlaarhoven** [janboone/applied-economics#37]
Hi,

I was wondering how important it is to do the last section of healthcare?

with model_2014:
    trace_2014 = pm.sample(n_samples,step = pm.Metropolis(),start = pm.find_MAP())

--> As of this code, I can't work on the assignment anymore, because running this cell takes too long (only 0.2% was loaded after 5 minutes, even when I brought down n_samples to 1).

**Comment by lindapelzer** [comment]
See the announcement on Canvas: IT cannot solve this in time. Hence you can stop before the section "reversing the probability distribution".

**Comment by janboone** [comment]
That is indeed weird; I will ask IT what is happening.

The last section is not important to do. The main point is to get the data on the jupyter server, read it into a dataframe and then get it into the right format.

The Bayesian analysis is just to show you what is possible in python; but then, of course, it should actually work.
