### ISSUE TITLE
Question about notebook for screencasts

### ISSUE THREAD

**Issue by qma9** [janboone/applied-economics#42]
Hi,

I was wondering if the Jupyter notebook that we fill out for the screencasts has to be submitted?
It is mentioned in the screencasts but then you state that the only evaluation is the final assignment on the outline.

Thanks,
Quentin

**Comment by janboone** [comment]
Hi Quentin,

No need to submit the notebooks for the screencasts. But you can send it to me if you have problems (e.g. errors that you cannot resolve). Or show the problems to me in class.

Indeed, only the final assignment needs to be submitted.

Does this help?

Regards,

Jan.

**Comment by qma9** [comment]
Thanks that clears it up for me,

Quentin
