### ISSUE TITLE
Importing csv files 

### ISSUE THREAD

**Issue by Cagil-kazancioglu** [janboone/applied-economics#44]
Hi, what is the exact code for importing csv files from my own documents into the Jupyterlab notebook of the university server? 

I was unable to import my own files with the given pandas code from the Datacamp lectures.  

Thanks.

**Comment by janboone** [comment]
Just to be sure: with "my own files" you mean files on your own computer?

That will not work; you first need to import the csv file to the server: 

- on the server click on the folder icon at the top left of your screen
- click the third (middle) icon which is an upward pointing arrow: "upload files"
- click on the file you want to upload from your computer
- once the file is on the server, you can use the pandas command to import the csv file

also see: https://janboone.github.io/applied-economics/pagescreencasts.html#upload_data_on_the_university_server

does this help?

**Comment by Cagil-kazancioglu** [comment]
Hello, yes I meant the files that are stored in my own computer. Hence different than the working directory the server uses. 

I've just seen that you have a screencast regarding this topic, this helps substantially. 

Many thanks.
