### ISSUE TITLE
Model 2014 does not run

### ISSUE THREAD

**Issue by SvenWil** [janboone/applied-economics#45]
I saw this question was already asked last year, but I could not respond to the conversation anymore since it is closed. I hope it is not to late to ask this, I was lagging a bit behind with the notebook.

JupyterLab seems to get stuck on the following block of code:

n_samples = 500

with model_2014:
    trace_2014 = pm.sample(n_samples,step = pm.Metropolis(),start = pm.find_MAP())

It runs very slowly, even when decreasing the sample size. 
Can this be solved? Or is it not important, as said in the conversation from last year.
Thank you in advance!

Kind regards,
Sven

**Comment by janboone** [comment]
Indeed, IT is working on this, but the sampling still does not work (is extremely slow). So you can skip this for now. If you are interested in Bayesian analysis, we will look into this in next semester's seminar datascience.

Regards,

Jan.

**Comment by SvenWil** [comment]
Okay, thank you!
