### ISSUE TITLE
Regarding uploading files on google colab

### ISSUE THREAD

**Issue by 211sk** [janboone/applied-economics#46]
For our python project, we are working on google colab for ease of collaboration in real time. The datasets we are working with are quite large in size (>180MBs), so what would be a more optimal way of uploading them, especially for submission. We were thinking to upload it to our google drive, and then mount that drive folder to the notebook using the code -

from google.colab import drive
drive.mount('/content/drive')

But if it would create issues later on when we are presenting our project, then we can go with another way too

**Comment by janboone** [comment]
it is perfectly fine to work with colabs. When you are finished upload the notebook on github. If the dataset is too big to upload on github, provide a link in the notebook to the dataset. That link could be to a folder on google drive that you share. Sometimes students use wetransfer as well.
