### ISSUE TITLE
Weird error on column country

### ISSUE THREAD

**Issue by brunoeduardosep** [janboone/applied-economics#47]
Can someone explain me why is it not reading the first column?

![image](https://user-images.githubusercontent.com/70025407/148280247-cb69f91b-992c-4472-a12f-13129d212398.png)

**Comment by janboone** [comment]
I cannot see where you define the dataframe, but most likely country is (part of) the dataframe's index.

If your dataframe is called =df=, do something like

df = df.reset_index()

or 

df.reset_index(inplace=True)

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html

does this help?

Jan.

**Comment by brunoeduardosep** [comment]
Indeed the solution was to reset the index!

Thank you
