### ISSUE TITLE
I have a question about plt.fill_between

### ISSUE THREAD

**Issue by lucdevries** [janboone/applied-economics#48]
We tried to fill in a specific part of one of our graphs between two x values using plt.fill_between, however it failed to work. We want to fill in the DWL part in the graph below but we cannot seem to get it right. Another problem we have encountered is for the producer surplus as the cut off seems to be somewhat diagonal while it should be fully vertical. Furthermore we tried to implement a line between DWL and Producer surplus and it did not go at the right coordinates.

Thanks in advance! 
Paul de Graaf and Luc de Vries.

![image](https://user-images.githubusercontent.com/90047670/149828083-9c383e75-67b7-47fa-bc54-46aad885e536.png)

![image](https://user-images.githubusercontent.com/90047670/149828263-9d1214dd-20d9-4b85-8287-3ca03cb57ef4.png)

**Comment by janboone** [comment]
There is quite a lot going on in your code. To be sure we are talking about the same thing, consider the following simpler code. Does this solve your problems?

```
def demand(p):
    return 1-p

def supply(p):
    return p

p = 0.6

range_p = np.linspace(0,1)
plt.plot(demand(range_p),range_p)
plt.plot(supply(range_p),range_p)
plt.hlines(p,0,demand(p))
plt.vlines(demand(p),demand(p),p)
range_d = np.linspace(0,demand(p))
plt.fill_between(range_d,1-range_d,[0.6 for d in range_d],color='y')

```

![fillbetween](https://user-images.githubusercontent.com/1701497/149906179-abdc220e-cdab-471b-a26d-477caf448f8e.png)

**Comment by lucdevries** [comment]
I simplified the code a bit and I have got it now. Thank you!
