### ISSUE TITLE
Prophet model gives different results on different computers

### ISSUE THREAD

**Issue by SiJoris** [janboone/applied-economics#53]
Hi,

In our project, we use the prophet model to predict the Covid-19 cases in the future. However, we noticed that on each computer we run our code, the forecasts slightly differ. For example, on one computer the result is an average of 17,146 cases in the next 10 days, whereas on another computer the result is 17,228. After looking at possibly different versions of the prophet model, or changes in the dataset, nothing of it seems to cause these differences. The only thing we could find had something to do with the way 'L-BFGS optimization terminates'. Is this something we can solve? Or is this 'normal'?

Thank you in advance!

Sigo & Juanita

**Comment by janboone** [comment]
Many optimization routines have random elements in them. So indeed it is possible that you get slightly different results if you run them.

**Comment by SiJoris** [comment]
Okay good to know!
Thanks!
