### ISSUE TITLE
Python adds an additional .0 to my Year column when I import it

### ISSUE THREAD

**Issue by 211sk** [janboone/applied-economics#54]
![image](https://user-images.githubusercontent.com/70709646/151011037-77d1c686-2fdc-4bbd-aa6b-52e2ed6fb410.png)

I imported the following dataset, and in the dataset, the year values do not contain ".0"
I tried the following code which are present in # but none of them seem to work. 
I want to merge the year and country variable together to create a column index4 which looks like AFG2018 not AFG2018.0

Thank you

**Comment by janboone** [comment]
you need to tell pandas that Year is date (not a real number): `pd.to_datetime(sae.Year, format='%Y')`

there is no need to merge two columns into one to get an index. You can make the combination of two columns an index. See the example here: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html

with `df.set_index(['year', 'month'])`
