### ISSUE TITLE
Query on selecting a paper for the final assignment (AEA1)

### ISSUE THREAD

**Issue by Robert-Github-2001** [janboone/applied-economics#55]
Dear prof. Boone,

For the final assignment of AEA1, I am considering to briefly elaborate on the theoretical model described in [Hanssen (2004)](https://www.aeaweb.org/articles?id=10.1257/0002828041464470). Can you please advice on whether the theoretical model in this paper could be appropiate to describe and make a brief extension on? The reasons I am asking this is (i) that the paper is not fully theoretical in nature (it also evaluates the model empirically) and (ii) that it involves the application of economic methodology/reasoning to a case of political economy, although I believe I would enjoy the challenge in trying to communicate this clearly.

Many thanks in advance.
Robert

Full reference:
Hanssen, F. A. (2004). Is there a politically optimal level of judicial independence?. American Economic Review, 94(3), 712-729.

**Comment by janboone** [comment]
Hi Robert,

The theoretical model calculates an equilibrium and therefore seems suitable for the final assignment. One thing you could do, is to calculate equilibria for a range of parameters and then use the empirical model in the paper on this simulated data. Does the empirical analysis correctly recover the parameters that you used in generating the data?

Regards,

Jan.

**Comment by Robert-Github-2001** [comment]
Thanks a lot for your fast reply! This seems very interesting, I will try to start with this in Python before the next tutorial (so that I may ask you for feedback then). 

Have a great day, Robert

**Comment by janboone** [comment]
Indeed, feel free to ask for feedback in the tutorials! That is why we have them...

**Comment by CAMSchraauwen1** [comment]
Hi! 

I have a similar paper in the sense that there is a theoretical model and empirical facts. Is the step that you propose (simulate the model and then check whether the empirical analysis correctly gets to these parameters) an extension I could do as well? 
My paper is the following: Bell, A.M., Chetty, R., Jaravel, X., Petkova, N., & Van Reenen, J. (2019). Do Tax Cuts Produce More Einsteins? The Impacts of Financial Incentives vs. Exposure to Innovation on the Supply of Investors. LSE Research Online Documents on Economics. https://doi.org/10.3386/w25493 

A difference between my paper and Robert's paper is that they already build the model such that it matches the empirical facts that they find. 

Thank you in advance! 

Regards, 
Britt

**Comment by janboone** [comment]
Indeed, if you simulate the model (in the way we do in class with creating an economy with, say, 10000 agents who get a draw from their innovation specific ability etc.) and then see whether you generate similar empirical observations that will be fine.

**Comment by CAMSchraauwen1** [comment]
Thank you for your fast reply! 
And do you think my paper is suitable for the assignment?

**Comment by janboone** [comment]
paper sounds fine to me.
