### ISSUE TITLE
Maths is not displayed clearly in the notebook for me

### ISSUE THREAD

**Issue by Robert-Github-2001** [janboone/applied-economics#56]
Hi,

I tried to start on the notebook assignment on gender economics, but unfortunately the maths is not displayed clearly in my notebook:

Can you please advice how to solve this issue so I could start working on the assignment?

Many thanks.

Kind regards, 
Robert

![afbeelding](https://user-images.githubusercontent.com/112098390/203065935-6d97fdba-2847-4d6c-840c-1dc5e473c086.png)

**Comment by Robert-Github-2001** [comment]
I'm not sure what happened exactly,  but it magically seems to work now. Please consider this remark solved and have a nice day.

**Comment by janboone** [comment]
glad to hear it is solved.
