### ISSUE TITLE
Question assignment loading real data into assignment

### ISSUE THREAD

**Issue by pepijnploegmakers** [janboone/applied-economics#59]
Dear Jan, 

For the assignment I have replicated a graph from the paper (The Problem of the Commons: Still Unsettled after 100 Years) which I use. To acces the data I have uploaded the csv file of the data used in the paper to the university Jupyter server in the same map as my assignment file and then used pd.read_csv() to open it. However i recently realised this code will probably not work when my assignment file is pushed to the github classroom.

I tried to use urlretrieve as an alternative but due to the nature of the site I could not figure it out. The site uses some sort of search engine where you can select type of fish and years etc. And then you can download it to your computer.(site:https://www.fao.org/fishery/statistics-query/en/capture/capture_quantity).
Is it possible to push the csv file of the data into the github classroom when also pushing my assignment file? Or is there a way to acces the data direct into my assignment file from the site in another way? 

Thank you in advance for your time and consideration.

Best, Pepijn Ploegmakers

**Comment by janboone** [comment]
Hi Pepijn,

Indeed, you can add the data to your github classroom repository. That should be no problem (unless the dataset is really big).

Regards, Jan.

**Comment by pepijnploegmakers** [comment]
Dear Jan,

Thank you for your quick reply, the dataset is not that big so I think I will be able to manage from here. 

Best, Pepijn Ploegmakers
