### ISSUE TITLE
Interactive graph for final assignment

### ISSUE THREAD

**Issue by jhermus** [janboone/applied-economics#6]
Dear Jan Boone,

for our final assignment we created an interactive graph in the Python notebook, and it works in the notebook. However, when we upload it to Github, in the output there is only an image. [Here](https://github.com/jhermus/Assignments/blob/master/Interactieve%20grafiek.ipynb) you can find our code, we hope you can tell what the issue is here.

We appreciate your help.

Best, 

Joep Hermus
Freek Heuvelmans

**Comment by juliengovaarts** [comment]
If it works in the notebook, this is fine. We clone your directory. If you want the on-line version to work, you try to export to html. Perhaps that will work as well.

**Comment by janboone** [comment]
sorry, I gave this answer.

Jan.

**Comment by jhermus** [comment]
Thank you!
