### ISSUE TITLE
Comment on uploading the assignment to Github

### ISSUE THREAD

**Issue by Robert-Github-2001** [janboone/applied-economics#64]
Dear professor Boone, 

Please consider this as a comment rather than a question: I sent you a message on Canvas as well, I just wanted to make sure that you would be able to see it before grading the assignments.

Several weeks ago during the Q&A, I created a repository with your help to upload the assignment of my group mate Quint Linderman and me. However, it appears as another student whom I do not know uploaded their own assignment by accident to this repository. Therefore, please consider the assignment uploaded by my team mate Quint as relevant for me (it also features my name and ANR/SNR), instead of the assignment found in the repository I created several weeks ago.

Many thanks. In case you have any questions or comments on the assignment of Quint and me, I would be happy to answer these of course.

Best regards,
Robert Schmitz

**Comment by janboone** [comment]
We have graded the assignments now. I think this has been resolved?

Regards,
Jan.

**Comment by Robert-Github-2001** [comment]
Dear prof. Boone,

I received the same grade on Osiris as my group mate. Therefore, the issue seems solved indeed.

Many thanks for this! Have a nice day.

Best,
Robert
